services:
  - type: web
    name: discord-music-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
